version: "3"

services:
  # web:
  #   build: "."
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - /dev/code/ch4-bookstore/
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - "db"


  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5431:5432 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_SERVER=127.0.0.1
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432 
      # - PGDATA=/var/lib/postgresql/data

volumes:
  postgres_data:
